### ISSUE TITLE
Crash when RedstoneRepository isn't installed

### ISSUE THREAD

**Issue by LemADEC** [CyberdyneCC/SimplyJetpacks-2#142]
As of SimplyJetpacks2-1.12.2-2.2.13.66, client crashes when wearing a jetpack with certain chargeable items while RedstoneRepository isn't installed.
This is reproduced when placing an ExtraCell2 Wireless Terminal (ExtraCells-1.12.2-2.6.2a) in a bauble slot. From a quick code review, this can happen with many energy based baubles.

```
java.lang.NoClassDefFoundError: thundr/redstonerepository/api/IArmorEnderium
	at tonius.simplyjetpacks.item.ItemJetpack.chargeInventory(ItemJetpack.java:551)
	at tonius.simplyjetpacks.item.ItemJetpack.onArmorTick(ItemJetpack.java:131)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:371)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: thundr.redstonerepository.api.IArmorEnderium
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 21 more
Caused by: java.lang.NullPointerException
```

**Comment by Tomson124** [comment]
Could you please provide more detail to reproducing this? E.g. which jetpack you did wear?

**Comment by gneumann333** [comment]
I was the Soularium Jetplate from Simple Jetpack, so the highest Tier down the Enerdio Route.
Also i had 2 Flux Cell/Capacitors in my ineventory set for charging all items.
And an EnderIO Wireless charger nearby
...all that might compounded the issue...

**Comment by LemADEC** [comment]
You can reproduce with Thermal Enderium armored jetpack in chest position and the ExtraCell2 Universal terminal in any bauble slot.

**Comment by gneumann333** [comment]
The Universal Terminal never made it into a Baubles slot. i turned the "normal" Terminal into the baubles version and when i took the newly crafted baubels version and tried to drop it into my inventory the game crashed.
Now the game crashes when i try to login to the Server

**Comment by Tomson124** [comment]
Should be fixed with the latest version. (2.2.14.67)
If not, feel free to reopen the issue.
