### ISSUE TITLE
Duplicate redstoneFlux mod in 1.12.1 and crash on first step

### ISSUE THREAD

**Issue by IcedReaper** [CyberdyneCC/SimplyJetpacks-2#38]
Hi,

I just tried to use the 1.12 Version of this mod and got an error while starting up the pack.
"You have mod sources that are duplicate within your system"

redstoneflux: RedstoneFlux-1.12-2.0.1.2-universal.jar
redstoneflux: SimplyJetpacks2-1.10.2-2.1.3.9.jar (I downloaded the latest 1.12 Version from Jenkins)

- I tried disabling the orginal redstoneflux mod with the twitch launcher and it disabled several other mods as their dependency is the redstoneflux lib.
- I tried removing the cofh folder from your jar (with winrar) (I know it's a dump idea) and it "worked". Minecraft started and the world loaded, but crashed on the first frame.
- Later I tried to manually remove the original redstoneflux lib (via explorer - not the twitch app) and it "worked". The world started, I could (in creative) give myself a jetpack, but just when I started walking the server closed the connection (local creative world).
- Furthermore I also tried to reduce the amount of mods (131 to 13 - with forge mods) and it crashed at the same position. As long as I didn't move everything was fine, but as soon as I started walking the server crashed.
The modlist of this try: 
    - CodeChickenLib-1.12-3.1.3.313-universal
    - CoFHCore-1.12-4.3.5.13-universal
    - CoFHWorld-1.12-1.0.1.8-universal
    - ThermalDynamics-1.12-2.3.5.12-universal
    - ThermalExpansion-1.12-5.3.5.19-universal
    - ThermalFoundation-1.12-2.3.5.14-universal
- The last try I did was to start only with SimplyJetpacks2 and that worked.

MC Version: 1.12.1
Forge Version: 14.22.0.2474

Here is the Errormessage (copied from the gameoutput)
`
There was a critical exception handling a packet on channel SimplyJetpacks
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:249)
	at tonius.simplyjetpacks.config.Config.onPlayerLoggon(Config.java:172)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_56_Config_onPlayerLoggon_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:573)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:218)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at tonius.simplyjetpacks.item.rewrite.Jetpack.writeConfigToNBT(Jetpack.java:346)
	at tonius.simplyjetpacks.item.rewrite.Jetpack.writeAllConfigsToNBT(Jetpack.java:257)
	at tonius.simplyjetpacks.network.message.MessageConfigSync.toBytes(MessageConfigSync.java:21)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:30)
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleIndexedCodec.encodeInto(SimpleIndexedCodec.java:26)
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:73)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	... 25 more
`

Thanks for your work in updating the mod to 1.12.

Thanks for your support.
IcedReaper

**Comment by Tomson124** [comment]
I know that, I had it in my development environment, too, I just disabled it (not possible outside the dev environment). I am currently working on it.

**Comment by IcedReaper** [comment]
Ok thanks for the heads up.

**Comment by JamiesWhiteShirt** [comment]
You are not supposed to repack the Redstone Flux API as of Minecraft 1.12. See [the Curseforge page](https://minecraft.curseforge.com/projects/redstone-flux).
