### ISSUE TITLE
[1.10.2-2.0.2.6] Broken textures on jetpack

### ISSUE THREAD

**Issue by RealGrep** [CyberdyneCC/SimplyJetpacks-2#4]
The tier 1 jetpack (and quite likely other ones) have the broken texture thing going on. In the log, I get this (short enough, I'll just paste it directly):

java.io.FileNotFoundException: simplyjetpacks:textures/armor/jetpackEIO1.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:28) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:67) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:42) [bwf.class:?]
	at net.minecraft.client.renderer.entity.Render.func_110776_a(SourceFile:98) [bsi.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_188361_a(LayerArmorBase.java:66) [buf.class:?]
	at net.minecraft.client.renderer.entity.layers.LayerArmorBase.func_177141_a(LayerArmorBase.java:39) [buf.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:436) [bsy.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:188) [bsy.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:70) [bvh.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28) [bvh.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366) [bsh.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:94) [bhc.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [bhc.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76) [bgl.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51) [bgw.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [bhc.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_102]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]

Other than key bindings not working, and this, it seems to work fairly well so far.

**Comment by Tomson124** [comment]
That is because I didn't got to updating the armor textures yet. I will look into that for the next build.

**Comment by Tomson124** [comment]
Should be fixed with latest version
